# The URL the site will be built for
base_url = "https://ksindi.com"

# The site title and description; used in feeds by default.
title = "Kamil Sindi"
description = "Just a place to write."

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Generate an Atom feed
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true

[markdown.highlighting]
theme = "dark-plus"

[extra]
katex_auto_render = true
menu = [
    { url = "/", name = "Home" },
    { url = "/blog", name = "Posts" },
    { url = "/reboot", name = "Reboot" },
    { url = "/bookshelf", name = "Bookshelf" },
    { url = "https://github.com/ksindi", name = "GitHub" },
    { url = "https://linkedin.com/in/kamilsindi", name = "LinkedIn" },
    { url = "https://x.com/kamilsindi", name = "X" },
    { url = "/atom.xml", name = "Feed" },
]
